namespace PUBGLibrary.Telemetry
{
    public enum EventType
    {
        LogCarePackageLand,
        LogCarePackageSpawn,
        LogGameStatePeriodic,
        LogItemAttach,
        LogItemDetach,
        LogItemDrop,
        LogItemEquip,
        LogItemPickup,
        LogItemUnequip,
        LogItemUse,
        LogMatchDefinition,
        LogMatchEnd,
        LogMatchStart,
        LogPlayerAttack,
        LogPlayerCreate,
        LogPlayerKill,
        LogPlayerLogin,
        LogPlayerLogout,
        LogPlayerPosition,
        LogPlayerTakeDamage,
        LogVehicleDestroy,
        LogVehicleLeave,
        LogVehicleRide,
        Unknown
    }
}
